server:
  port: 8081

dubbo:
  application:
    name: sentinel-producer
  registry:
    address: zookeeper://192.168.1.23:2181?backup=192.168.1.24:2181,192.168.1.25:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 20885
  config-center:
    timeout: 5000

spring:
  application:
    name: baobanserver
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
