server:
  port: 8084

dubbo:
  application:
    name: seata-order
  registry:
    address: zookeeper://192.168.1.23:2181?backup=192.168.1.24:2181,192.168.1.25:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 20886
  config-center:
    timeout: 5000

spring:
  datasource:
    url: jdbc:mysql://192.168.1.26:3306/db_seata?characterEncoding=utf8
    username: time
    password: time25!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
